dependency:
  name: galaxy
driver:
  name: docker
lint: |-
  set -e
  yamllint .
  ansible-lint
platforms:
  - command: /usr/lib/systemd/systemd --system
    environment:
      container: docker
    groups:
      - docker
    name: rocky-8
    image: rockylinux/rockylinux:latest
    privileged: true
    tty: false
    volume:
      - /sys/fs/cgroup
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  log: true
  name: ansible
  options:
    vvv: false
verifier:
  name: ansible
