- hosts: all
  name: MOLECULE | Prepare
  tasks:
  - name: install required software
    package:
      name:
        - authselect
        - crypto-policies-scripts
        - dbus
        - cronie
        - grub2
        - module-init-tools
        - openssh
        - openssh-server
        - python3-libselinux
        - python3
        - python3-rpm
        - selinux-policy
        - sudo
        - systemd-container
      state: present
  - name: Start service sshd
    service:
      name: sshd
      state: started
